# Generated by Django 5.0.6 on 2024-07-07 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(default=datetime.datetime.now, max_length=255),
            preserve_default=False,
        ),
    ]
