# Generated by Django 5.0.6 on 2024-07-07 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
